/**
 * Downloads the two app typefaces from Google Fonts into public/fonts/ and writes
 * src/styles/fonts.css pointing at the local copies.
 *
 * WeekFlow is offline-first, so it cannot depend on a font CDN at runtime — an APK
 * on a plane must still look like WeekFlow. Run this once; the results are committed.
 *
 *   node scripts/vendor-fonts.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'styles', 'fonts.css');

// A modern UA is required or Google serves ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  {
    name: 'Fraunces',
    // opsz is what gives Fraunces its character at display sizes.
    query: 'Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400',
    slug: 'fraunces',
  },
  {
    name: 'Plus Jakarta Sans',
    query: 'Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;1,500',
    slug: 'jakarta',
  },
];

// Subsets we ship. Dropping cyrillic/greek/vietnamese saves ~60% with no loss for
// this app's languages; latin-ext carries the currency symbols we use.
const KEEP = new Set(['latin', 'latin-ext']);

async function get(url, asText = true) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asText ? res.text() : Buffer.from(await res.arrayBuffer());
}

/** Google's CSS is a sequence of `/* subset *\/ @font-face { ... }` blocks. */
function parseBlocks(css) {
  const out = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) out.push({ subset: m[1], block: m[2] });
  return out;
}

const field = (block, prop) => block.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim() ?? '';

/** "400" -> [400,400]; "100 900" -> [100,900] */
const weightRange = (s) => {
  const n = (s || '400').trim().split(/\s+/).map(Number);
  return [n[0], n.length > 1 ? n[1] : n[0]];
};

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });
  await fs.mkdir(path.dirname(CSS_OUT), { recursive: true });
  const rules = [];
  let total = 0;

  for (const fam of FAMILIES) {
    const css = await get(`https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`);
    const blocks = parseBlocks(css).filter((b) => KEEP.has(b.subset));
    if (!blocks.length) throw new Error(`No usable subsets returned for ${fam.name}`);

    /* These are variable fonts, so every requested weight resolves to the *same* file.
       Group by subset+style, download once, and emit one face with a weight range. */
    const faces = new Map();
    for (const { subset, block } of blocks) {
      const url = field(block, 'src').match(/url\((https:\/\/[^)]+)\)/)?.[1];
      if (!url) continue;
      const style = field(block, 'font-style') || 'normal';
      const key = `${subset}|${style}|${url}`;
      const [lo, hi] = weightRange(field(block, 'font-weight'));
      const cur = faces.get(key);
      if (cur) {
        cur.lo = Math.min(cur.lo, lo);
        cur.hi = Math.max(cur.hi, hi);
      } else {
        faces.set(key, { subset, style, url, lo, hi, range: field(block, 'unicode-range') });
      }
    }

    for (const f of faces.values()) {
      const file = `${fam.slug}-${f.subset}-${f.style}.woff2`;
      const bytes = await get(f.url, false);
      await fs.writeFile(path.join(OUT_DIR, file), bytes);
      total += bytes.length;

      rules.push(
        [
          '@font-face {',
          `  font-family: '${fam.name}';`,
          `  font-style: ${f.style};`,
          `  font-weight: ${f.lo === f.hi ? f.lo : `${f.lo} ${f.hi}`};`,
          '  font-display: swap;',
          `  src: url('/fonts/${file}') format('woff2');`,
          `  unicode-range: ${f.range};`,
          '}',
        ].join('\n'),
      );
      console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} KB  (weight ${f.lo}-${f.hi})`);
    }
  }

  const header =
    '/* Generated by scripts/vendor-fonts.mjs — do not edit by hand.\n' +
    '   Fonts are bundled so WeekFlow renders correctly with no network. */\n\n';
  await fs.writeFile(CSS_OUT, header + rules.join('\n\n') + '\n');
  console.log(`\n${rules.length} faces, ${(total / 1024).toFixed(0)} KB total -> src/styles/fonts.css`);
}

main().catch((err) => {
  console.error('Font vendoring failed:', err.message);
  process.exit(1);
});
